// seedStocks.js
require('dotenv').config();
const mongoose = require('mongoose');
const Stock = require('./models/stock'); // adjust path if needed

const initialStocks = [
  {
    stock_name: 'AAPL',
    company_name: 'Apple Inc.',
    open: 175.00,
    upper_circuit: 183.75,
    lower_circuit: 166.25,
    qty: 1432,
    sector: 'Technology',
    market_cap: 2900,
    pe_ratio: 28.5,
    dividend_yield: 0.6,
    about: 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, and wearables.',
    headquarters: 'Cupertino, California, USA',
    ceo: 'Tim Cook',
    founded_year: 1976,
    logo_url: 'https://logo.clearbit.com/apple.com',
    website: 'https://www.apple.com',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'MSFT',
    company_name: 'Microsoft Corp.',
    open: 330.00,
    upper_circuit: 346.50,
    lower_circuit: 313.50,
    qty: 973,
    sector: 'Technology',
    market_cap: 2700,
    pe_ratio: 35.1,
    dividend_yield: 0.8,
    about: 'Microsoft develops, licenses, and supports a range of software products, services, and devices.',
    headquarters: 'Redmond, Washington, USA',
    ceo: 'Satya Nadella',
    founded_year: 1975,
    logo_url: 'https://logo.clearbit.com/microsoft.com',
    website: 'https://www.microsoft.com',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'GOOGL',
    company_name: 'Alphabet Inc.',
    open: 145.00,
    upper_circuit: 152.25,
    lower_circuit: 137.75,
    qty: 2586,
    sector: 'Technology',
    market_cap: 2000,
    pe_ratio: 25.4,
    dividend_yield: 0.0,
    about: 'Alphabet Inc. is the parent company of Google and several former Google subsidiaries.',
    headquarters: 'Mountain View, California, USA',
    ceo: 'Sundar Pichai',
    founded_year: 1998,
    logo_url: 'https://logo.clearbit.com/abc.xyz',
    website: 'https://abc.xyz',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'AMZN',
    company_name: 'Amazon.com, Inc.',
    open: 135.00,
    upper_circuit: 141.75,
    lower_circuit: 128.25,
    qty: 731,
    sector: 'Consumer Discretionary',
    market_cap: 1700,
    pe_ratio: 60.2,
    dividend_yield: 0.0,
    about: 'Amazon is a multinational technology company focusing on e-commerce, cloud computing, and AI.',
    headquarters: 'Seattle, Washington, USA',
    ceo: 'Andy Jassy',
    founded_year: 1994,
    logo_url: 'https://logo.clearbit.com/amazon.com',
    website: 'https://www.amazon.com',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'TSLA',
    company_name: 'Tesla, Inc.',
    open: 264.00,
    upper_circuit: 277.20,
    lower_circuit: 250.80,
    qty: 1924,
    sector: 'Automotive',
    market_cap: 820,
    pe_ratio: 75.3,
    dividend_yield: 0.0,
    about: 'Tesla designs, manufactures, and sells electric vehicles, energy storage systems, and solar products.',
    headquarters: 'Austin, Texas, USA',
    ceo: 'Elon Musk',
    founded_year: 2003,
    logo_url: 'https://logo.clearbit.com/tesla.com',
    website: 'https://www.tesla.com',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'META',
    company_name: 'Meta Platforms, Inc.',
    open: 330.00,
    upper_circuit: 346.50,
    lower_circuit: 313.50,
    qty: 1478,
    sector: 'Technology',
    market_cap: 1100,
    pe_ratio: 29.9,
    dividend_yield: 0.5,
    about: 'Meta develops social media applications including Facebook, Instagram, and WhatsApp.',
    headquarters: 'Menlo Park, California, USA',
    ceo: 'Mark Zuckerberg',
    founded_year: 2004,
    logo_url: 'https://logo.clearbit.com/meta.com',
    website: 'https://about.meta.com',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'NVDA',
    company_name: 'NVIDIA Corp.',
    open: 470.00,
    upper_circuit: 493.50,
    lower_circuit: 446.50,
    qty: 873,
    sector: 'Technology',
    market_cap: 2800,
    pe_ratio: 50.7,
    dividend_yield: 0.03,
    about: 'NVIDIA designs graphics processing units (GPUs) for gaming and AI markets.',
    headquarters: 'Santa Clara, California, USA',
    ceo: 'Jensen Huang',
    founded_year: 1993,
    logo_url: 'https://logo.clearbit.com/nvidia.com',
    website: 'https://www.nvidia.com',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'JPM',
    company_name: 'JPMorgan Chase & Co.',
    open: 155.00,
    upper_circuit: 162.75,
    lower_circuit: 147.25,
    qty: 621,
    sector: 'Financials',
    market_cap: 550,
    pe_ratio: 10.8,
    dividend_yield: 2.9,
    about: 'JPMorgan Chase is one of the largest banking institutions in the United States.',
    headquarters: 'New York City, New York, USA',
    ceo: 'Jamie Dimon',
    founded_year: 2000,
    logo_url: 'https://logo.clearbit.com/jpmorganchase.com',
    website: 'https://www.jpmorganchase.com',
    stock_exchange: 'NYSE',
    currency: 'USD'
  },
  {
    stock_name: 'V',
    company_name: 'Visa Inc.',
    open: 250.00,
    upper_circuit: 262.50,
    lower_circuit: 237.50,
    qty: 3025,
    sector: 'Financials',
    market_cap: 500,
    pe_ratio: 32.6,
    dividend_yield: 0.7,
    about: 'Visa Inc. is a global payments technology company facilitating electronic funds transfers.',
    headquarters: 'San Francisco, California, USA',
    ceo: 'Ryan McInerney',
    founded_year: 1958,
    logo_url: 'https://logo.clearbit.com/visa.com',
    website: 'https://www.visa.com',
    stock_exchange: 'NYSE',
    currency: 'USD'
  },
  {
    stock_name: 'WMT',
    company_name: 'Walmart Inc.',
    open: 150.00,
    upper_circuit: 157.50,
    lower_circuit: 142.50,
    qty: 1594,
    sector: 'Consumer Staples',
    market_cap: 430,
    pe_ratio: 28.2,
    dividend_yield: 1.6,
    about: 'Walmart Inc. operates a chain of hypermarkets, discount department stores, and grocery stores.',
    headquarters: 'Bentonville, Arkansas, USA',
    ceo: 'Doug McMillon',
    founded_year: 1962,
    logo_url: 'https://logo.clearbit.com/walmart.com',
    website: 'https://www.walmart.com',
    stock_exchange: 'NYSE',
    currency: 'USD'
  },
  {
    stock_name: 'JNJ',
    company_name: 'Johnson & Johnson',
    open: 165.00,
    upper_circuit: 173.25,
    lower_circuit: 156.75,
    qty: 874,
    sector: 'Healthcare',
    market_cap: 420,
    pe_ratio: 25.7,
    dividend_yield: 2.7,
    about: 'Johnson & Johnson develops medical devices, pharmaceuticals, and consumer packaged goods.',
    headquarters: 'New Brunswick, New Jersey, USA',
    ceo: 'Joaquin Duato',
    founded_year: 1886,
    logo_url: 'https://logo.clearbit.com/jnj.com',
    website: 'https://www.jnj.com',
    stock_exchange: 'NYSE',
    currency: 'USD'
  },
  {
    stock_name: 'PG',
    company_name: 'Procter & Gamble',
    open: 145.00,
    upper_circuit: 152.25,
    lower_circuit: 137.75,
    qty: 1306,
    sector: 'Consumer Staples',
    market_cap: 380,
    pe_ratio: 24.8,
    dividend_yield: 2.5,
    about: 'Procter & Gamble is a multinational consumer goods corporation.',
    headquarters: 'Cincinnati, Ohio, USA',
    ceo: 'Jon R. Moeller',
    founded_year: 1837,
    logo_url: 'https://logo.clearbit.com/pg.com',
    website: 'https://www.pg.com',
    stock_exchange: 'NYSE',
    currency: 'USD'
  },
  {
    stock_name: 'DIS',
    company_name: 'The Walt Disney Co.',
    open: 110.00,
    upper_circuit: 115.50,
    lower_circuit: 104.50,
    qty: 1120,
    sector: 'Communication Services',
    market_cap: 180,
    pe_ratio: 21.3,
    dividend_yield: 1.2,
    about: 'The Walt Disney Company is a diversified international family entertainment and media enterprise.',
    headquarters: 'Burbank, California, USA',
    ceo: 'Bob Iger',
    founded_year: 1923,
    logo_url: 'https://logo.clearbit.com/disney.com',
    website: 'https://www.disney.com',
    stock_exchange: 'NYSE',
    currency: 'USD'
  },
  {
    stock_name: 'NFLX',
    company_name: 'Netflix, Inc.',
    open: 425.00,
    upper_circuit: 446.25,
    lower_circuit: 403.75,
    qty: 1789,
    sector: 'Communication Services',
    market_cap: 200,
    pe_ratio: 36.5,
    dividend_yield: 0.0,
    about: 'Netflix provides streaming entertainment services and produces original programming.',
    headquarters: 'Los Gatos, California, USA',
    ceo: 'Ted Sarandos',
    founded_year: 1997,
    logo_url: 'https://logo.clearbit.com/netflix.com',
    website: 'https://www.netflix.com',
    stock_exchange: 'NASDAQ',
    currency: 'USD'
  },
  {
    stock_name: 'BAC',
    company_name: 'Bank of America',
    open: 30.00,
    upper_circuit: 31.50,
    lower_circuit: 28.50,
    qty: 985,
    sector: 'Financials',
    market_cap: 260,
    pe_ratio: 9.5,
    dividend_yield: 3.1,
    about: 'Bank of America is a multinational investment bank and financial services company.',
    headquarters: 'Charlotte, North Carolina, USA',
    ceo: 'Brian Moynihan',
    founded_year: 1904,
    logo_url: 'https://logo.clearbit.com/bankofamerica.com',
    website: 'https://www.bankofamerica.com',
    stock_exchange: 'NYSE',
    currency: 'USD'
  }
];


async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('MongoDB connected');

    // Remove any existing docs (optional)
    await Stock.deleteMany({});
    console.log('Cleared old stock data');

    // Insert the initial batch
    const docs = await Stock.insertMany(initialStocks);
    console.log(`Inserted ${docs.length} stocks`);

    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

seed();
